import type { AdInsightRow, VideoRetention } from "@/lib/types";

/** Dados mockados no estilo Meta Ads / ULBRA para validar o layout. */
const RAW_MOCK_INSIGHTS = [
  // Campanha Vestibular 2026 — Conjunto Lookalike
  {
    ad_id: "ad_1001",
    ad_name: "Vestibular 2026 — Bolsa 50%",
    adset_id: "as_201",
    adset_name: "LAL 1% Engajados",
    campaign_id: "camp_10",
    campaign_name: "Vestibular 2026 — Conversão",
    date_start: "2026-08-05",
    date_stop: "2026-08-05",
    spend: 312.4,
    impressions: 18420,
    clicks: 412,
    ctr: 2.24,
    cpc: 0.76,
    cpm: 16.96,
    results: 28,
    cost_per_result: 11.16,
    headline: "Bolsa de até 50% no Vestibular ULBRA",
    primary_text:
      "Garanta sua vaga no Vestibular 2026 com bolsa de até 50%. Inscrições abertas. Estude na universidade que forma profissionais de verdade.",
    description: "Inscreva-se online em poucos minutos.",
    call_to_action: "INSCREVER_SE",
    image_url: null,
    video_id: null,
    link_url: "https://ulbra.br/vestibular",
  },
  {
    ad_id: "ad_1001",
    ad_name: "Vestibular 2026 — Bolsa 50%",
    adset_id: "as_201",
    adset_name: "LAL 1% Engajados",
    campaign_id: "camp_10",
    campaign_name: "Vestibular 2026 — Conversão",
    date_start: "2026-08-06",
    date_stop: "2026-08-06",
    spend: 298.1,
    impressions: 17200,
    clicks: 389,
    ctr: 2.26,
    cpc: 0.77,
    cpm: 17.33,
    results: 31,
    cost_per_result: 9.62,
    headline: "Bolsa de até 50% no Vestibular ULBRA",
    primary_text:
      "Garanta sua vaga no Vestibular 2026 com bolsa de até 50%. Inscrições abertas. Estude na universidade que forma profissionais de verdade.",
    description: "Inscreva-se online em poucos minutos.",
    call_to_action: "INSCREVER_SE",
    image_url: null,
    video_id: null,
    link_url: "https://ulbra.br/vestibular",
  },
  {
    ad_id: "ad_1001",
    ad_name: "Vestibular 2026 — Bolsa 50%",
    adset_id: "as_201",
    adset_name: "LAL 1% Engajados",
    campaign_id: "camp_10",
    campaign_name: "Vestibular 2026 — Conversão",
    date_start: "2026-08-07",
    date_stop: "2026-08-07",
    spend: 341.8,
    impressions: 20110,
    clicks: 455,
    ctr: 2.26,
    cpc: 0.75,
    cpm: 17.0,
    results: 35,
    cost_per_result: 9.77,
    headline: "Bolsa de até 50% no Vestibular ULBRA",
    primary_text:
      "Garanta sua vaga no Vestibular 2026 com bolsa de até 50%. Inscrições abertas. Estude na universidade que forma profissionais de verdade.",
    description: "Inscreva-se online em poucos minutos.",
    call_to_action: "INSCREVER_SE",
    image_url: null,
    video_id: null,
    link_url: "https://ulbra.br/vestibular",
  },
  {
    ad_id: "ad_1002",
    ad_name: "Vestibular 2026 — Prova Online",
    adset_id: "as_201",
    adset_name: "LAL 1% Engajados",
    campaign_id: "camp_10",
    campaign_name: "Vestibular 2026 — Conversão",
    date_start: "2026-08-05",
    date_stop: "2026-08-05",
    spend: 187.5,
    impressions: 11200,
    clicks: 198,
    ctr: 1.77,
    cpc: 0.95,
    cpm: 16.74,
    results: 12,
    cost_per_result: 15.63,
    headline: "Faça a prova do Vestibular online",
    primary_text:
      "Sem deslocamento, sem fila. Faça a prova do Vestibular ULBRA de onde estiver e conquiste sua vaga.",
    description: "Prova 100% online.",
    call_to_action: "SAIBA_MAIS",
    image_url: null,
    video_id: "vid_8821",
    link_url: "https://ulbra.br/vestibular",
  },
  {
    ad_id: "ad_1002",
    ad_name: "Vestibular 2026 — Prova Online",
    adset_id: "as_201",
    adset_name: "LAL 1% Engajados",
    campaign_id: "camp_10",
    campaign_name: "Vestibular 2026 — Conversão",
    date_start: "2026-08-08",
    date_stop: "2026-08-08",
    spend: 210.2,
    impressions: 12880,
    clicks: 221,
    ctr: 1.72,
    cpc: 0.95,
    cpm: 16.32,
    results: 14,
    cost_per_result: 15.01,
    headline: "Faça a prova do Vestibular online",
    primary_text:
      "Sem deslocamento, sem fila. Faça a prova do Vestibular ULBRA de onde estiver e conquiste sua vaga.",
    description: "Prova 100% online.",
    call_to_action: "SAIBA_MAIS",
    image_url: null,
    video_id: "vid_8821",
    link_url: "https://ulbra.br/vestibular",
  },
  {
    ad_id: "ad_1003",
    ad_name: "Vestibular — Interesse Medicina",
    adset_id: "as_202",
    adset_name: "Interesse Medicina 18-24",
    campaign_id: "camp_10",
    campaign_name: "Vestibular 2026 — Conversão",
    date_start: "2026-08-06",
    date_stop: "2026-08-06",
    spend: 520.0,
    impressions: 24500,
    clicks: 310,
    ctr: 1.27,
    cpc: 1.68,
    cpm: 21.22,
    results: 9,
    cost_per_result: 57.78,
    headline: "Medicina ULBRA: sua carreira começa aqui",
    primary_text:
      "Infraestrutura de ponta, corpo docente experiente e formação humanizada. Conheça o curso de Medicina da ULBRA e candidate-se ao Vestibular.",
    description: "Vagas limitadas.",
    call_to_action: "INSCREVER_SE",
    image_url: null,
    video_id: null,
    link_url: "https://ulbra.br/medicina",
  },
  {
    ad_id: "ad_1003",
    ad_name: "Vestibular — Interesse Medicina",
    adset_id: "as_202",
    adset_name: "Interesse Medicina 18-24",
    campaign_id: "camp_10",
    campaign_name: "Vestibular 2026 — Conversão",
    date_start: "2026-08-09",
    date_stop: "2026-08-09",
    spend: 498.6,
    impressions: 23100,
    clicks: 287,
    ctr: 1.24,
    cpc: 1.74,
    cpm: 21.58,
    results: 8,
    cost_per_result: 62.33,
    headline: "Medicina ULBRA: sua carreira começa aqui",
    primary_text:
      "Infraestrutura de ponta, corpo docente experiente e formação humanizada. Conheça o curso de Medicina da ULBRA e candidate-se ao Vestibular.",
    description: "Vagas limitadas.",
    call_to_action: "INSCREVER_SE",
    image_url: null,
    video_id: null,
    link_url: "https://ulbra.br/medicina",
  },
  // Campanha Remarketing
  {
    ad_id: "ad_2001",
    ad_name: "RMK — Abandonou inscrição",
    adset_id: "as_301",
    adset_name: "Site visitors 7d",
    campaign_id: "camp_20",
    campaign_name: "Remarketing Vestibular",
    date_start: "2026-08-07",
    date_stop: "2026-08-07",
    spend: 95.4,
    impressions: 8200,
    clicks: 268,
    ctr: 3.27,
    cpc: 0.36,
    cpm: 11.63,
    results: 22,
    cost_per_result: 4.34,
    headline: "Falta pouco pra garantir sua vaga",
    primary_text:
      "Você começou a inscrição e não terminou. Finalize agora e concorra a bolsas no Vestibular ULBRA 2026.",
    description: "Retome de onde parou.",
    call_to_action: "INSCREVER_SE",
    image_url: null,
    video_id: null,
    link_url: "https://ulbra.br/vestibular/continuar",
  },
  {
    ad_id: "ad_2001",
    ad_name: "RMK — Abandonou inscrição",
    adset_id: "as_301",
    adset_name: "Site visitors 7d",
    campaign_id: "camp_20",
    campaign_name: "Remarketing Vestibular",
    date_start: "2026-08-08",
    date_stop: "2026-08-08",
    spend: 102.1,
    impressions: 9100,
    clicks: 291,
    ctr: 3.2,
    cpc: 0.35,
    cpm: 11.22,
    results: 25,
    cost_per_result: 4.08,
    headline: "Falta pouco pra garantir sua vaga",
    primary_text:
      "Você começou a inscrição e não terminou. Finalize agora e concorra a bolsas no Vestibular ULBRA 2026.",
    description: "Retome de onde parou.",
    call_to_action: "INSCREVER_SE",
    image_url: null,
    video_id: null,
    link_url: "https://ulbra.br/vestibular/continuar",
  },
  {
    ad_id: "ad_2001",
    ad_name: "RMK — Abandonou inscrição",
    adset_id: "as_301",
    adset_name: "Site visitors 7d",
    campaign_id: "camp_20",
    campaign_name: "Remarketing Vestibular",
    date_start: "2026-08-10",
    date_stop: "2026-08-10",
    spend: 88.7,
    impressions: 7650,
    clicks: 245,
    ctr: 3.2,
    cpc: 0.36,
    cpm: 11.59,
    results: 19,
    cost_per_result: 4.67,
    headline: "Falta pouco pra garantir sua vaga",
    primary_text:
      "Você começou a inscrição e não terminou. Finalize agora e concorra a bolsas no Vestibular ULBRA 2026.",
    description: "Retome de onde parou.",
    call_to_action: "INSCREVER_SE",
    image_url: null,
    video_id: null,
    link_url: "https://ulbra.br/vestibular/continuar",
  },
  {
    ad_id: "ad_2002",
    ad_name: "RMK — Engajamento Instagram",
    adset_id: "as_302",
    adset_name: "Engajados IG 30d",
    campaign_id: "camp_20",
    campaign_name: "Remarketing Vestibular",
    date_start: "2026-08-09",
    date_stop: "2026-08-09",
    spend: 64.3,
    impressions: 15200,
    clicks: 420,
    ctr: 2.76,
    cpc: 0.15,
    cpm: 4.23,
    results: 11,
    cost_per_result: 5.85,
    headline: "Ainda dá tempo de se inscrever",
    primary_text:
      "Quem acompanha a ULBRA no Instagram já sabe: o Vestibular 2026 está aberto. Clique e confirme sua inscrição.",
    description: null,
    call_to_action: "SAIBA_MAIS",
    image_url: null,
    video_id: null,
    link_url: "https://ulbra.br/vestibular",
  },
  // Campanha Awareness
  {
    ad_id: "ad_3001",
    ad_name: "Brand — Campus Tour",
    adset_id: "as_401",
    adset_name: "Broad 18-30 RS",
    campaign_id: "camp_30",
    campaign_name: "Awareness Marca ULBRA",
    date_start: "2026-08-04",
    date_stop: "2026-08-04",
    spend: 180.0,
    impressions: 62000,
    clicks: 890,
    ctr: 1.44,
    cpc: 0.2,
    cpm: 2.9,
    results: 0,
    cost_per_result: 0,
    headline: "Conheça o campus ULBRA",
    primary_text:
      "Laboratórios, biblioteca, arenas esportivas e uma comunidade que transforma. Venha viver a experiência ULBRA.",
    description: "Agende uma visita.",
    call_to_action: "SAIBA_MAIS",
    image_url: null,
    video_id: "vid_4401",
    link_url: "https://ulbra.br/campus",
  },
  {
    ad_id: "ad_3001",
    ad_name: "Brand — Campus Tour",
    adset_id: "as_401",
    adset_name: "Broad 18-30 RS",
    campaign_id: "camp_30",
    campaign_name: "Awareness Marca ULBRA",
    date_start: "2026-08-11",
    date_stop: "2026-08-11",
    spend: 175.5,
    impressions: 58400,
    clicks: 812,
    ctr: 1.39,
    cpc: 0.22,
    cpm: 3.01,
    results: 0,
    cost_per_result: 0,
    headline: "Conheça o campus ULBRA",
    primary_text:
      "Laboratórios, biblioteca, arenas esportivas e uma comunidade que transforma. Venha viver a experiência ULBRA.",
    description: "Agende uma visita.",
    call_to_action: "SAIBA_MAIS",
    image_url: null,
    video_id: "vid_4401",
    link_url: "https://ulbra.br/campus",
  },
  {
    ad_id: "ad_3002",
    ad_name: "Brand — Depoimento Aluno",
    adset_id: "as_401",
    adset_name: "Broad 18-30 RS",
    campaign_id: "camp_30",
    campaign_name: "Awareness Marca ULBRA",
    date_start: "2026-08-10",
    date_stop: "2026-08-10",
    spend: 142.8,
    impressions: 48100,
    clicks: 654,
    ctr: 1.36,
    cpc: 0.22,
    cpm: 2.97,
    results: 0,
    cost_per_result: 0,
    headline: "“A ULBRA mudou minha trajetória”",
    primary_text:
      "Assista ao depoimento de quem já viveu a formação completa: prática, networking e propósito. Sua história também pode começar aqui.",
    description: "Depoimento real.",
    call_to_action: "ASSISTIR_MAIS",
    image_url: null,
    video_id: "vid_4410",
    link_url: "https://ulbra.br",
  },
  // EAD
  {
    ad_id: "ad_4001",
    ad_name: "EAD — Flexibilidade",
    adset_id: "as_501",
    adset_name: "Interesse Graduação EAD",
    campaign_id: "camp_40",
    campaign_name: "Captação EAD 2026/2",
    date_start: "2026-08-05",
    date_stop: "2026-08-05",
    spend: 230.4,
    impressions: 19800,
    clicks: 502,
    ctr: 2.54,
    cpc: 0.46,
    cpm: 11.64,
    results: 41,
    cost_per_result: 5.62,
    headline: "Graduação EAD com diploma reconhecido",
    primary_text:
      "Estude no seu ritmo, com tutoria e material completo. Cursos EAD ULBRA com a mesma qualidade do presencial.",
    description: "Matrículas abertas.",
    call_to_action: "INSCREVER_SE",
    image_url: null,
    video_id: null,
    link_url: "https://ulbra.br/ead",
  },
  {
    ad_id: "ad_4001",
    ad_name: "EAD — Flexibilidade",
    adset_id: "as_501",
    adset_name: "Interesse Graduação EAD",
    campaign_id: "camp_40",
    campaign_name: "Captação EAD 2026/2",
    date_start: "2026-08-11",
    date_stop: "2026-08-11",
    spend: 255.9,
    impressions: 21450,
    clicks: 548,
    ctr: 2.55,
    cpc: 0.47,
    cpm: 11.93,
    results: 47,
    cost_per_result: 5.44,
    headline: "Graduação EAD com diploma reconhecido",
    primary_text:
      "Estude no seu ritmo, com tutoria e material completo. Cursos EAD ULBRA com a mesma qualidade do presencial.",
    description: "Matrículas abertas.",
    call_to_action: "INSCREVER_SE",
    image_url: null,
    video_id: null,
    link_url: "https://ulbra.br/ead",
  },
  {
    ad_id: "ad_4002",
    ad_name: "EAD — Preço promocional",
    adset_id: "as_502",
    adset_name: "Lookalike leads EAD",
    campaign_id: "camp_40",
    campaign_name: "Captação EAD 2026/2",
    date_start: "2026-08-08",
    date_stop: "2026-08-08",
    spend: 190.0,
    impressions: 16700,
    clicks: 378,
    ctr: 2.26,
    cpc: 0.5,
    cpm: 11.38,
    results: 29,
    cost_per_result: 6.55,
    headline: "Mensalidade a partir de R$ 199",
    primary_text:
      "Condições especiais para novos alunos EAD. Escolha seu curso e comece ainda neste semestre.",
    description: "Oferta por tempo limitado.",
    call_to_action: "COMPRAR",
    image_url: null,
    video_id: null,
    link_url: "https://ulbra.br/ead/oferta",
  },
  {
    ad_id: "ad_4002",
    ad_name: "EAD — Preço promocional",
    adset_id: "as_502",
    adset_name: "Lookalike leads EAD",
    campaign_id: "camp_40",
    campaign_name: "Captação EAD 2026/2",
    date_start: "2026-08-10",
    date_stop: "2026-08-10",
    spend: 205.5,
    impressions: 17920,
    clicks: 401,
    ctr: 2.24,
    cpc: 0.51,
    cpm: 11.47,
    results: 33,
    cost_per_result: 6.23,
    headline: "Mensalidade a partir de R$ 199",
    primary_text:
      "Condições especiais para novos alunos EAD. Escolha seu curso e comece ainda neste semestre.",
    description: "Oferta por tempo limitado.",
    call_to_action: "COMPRAR",
    image_url: null,
    video_id: null,
    link_url: "https://ulbra.br/ead/oferta",
  },
];

const SAMPLE_VIDEOS = {
  campus:
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
  prova:
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  depoimento:
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
} as const;

/** Thumbnails + vídeos de exemplo por ad_id (picsum + samples públicos). */
const CREATIVE_MEDIA: Record<
  string,
  {
    image_url: string;
    video_id: string | null;
    video_storage_url: string | null;
    video_transcript: string | null;
    video_retention: VideoRetention | null;
  }
> = {
  ad_1001: {
    image_url: "https://picsum.photos/seed/ulbra-bolsa/600/750",
    video_id: null,
    video_storage_url: null,
    video_transcript: null,
    video_retention: null,
  },
  // Queda no CTA / final — com transcrição
  ad_1002: {
    image_url: "https://picsum.photos/seed/ulbra-prova/600/750",
    video_id: "vid_8821",
    video_storage_url: SAMPLE_VIDEOS.prova,
    video_transcript:
      "Ei, você sabia que dá pra fazer a prova do Vestibular ULBRA 100% online?\nSem deslocamento, sem fila, sem estresse.\nEm poucos minutos você garante sua inscrição e disputa sua vaga.\nClica no botão e começa agora — as bolsas estão abertas.",
    video_retention: {
      plays: 8200,
      avg_watch_time_sec: 18.2,
      duration_sec: 32,
      p25: 78,
      p50: 64,
      p75: 51,
      p95: 28,
      p100: 12,
    },
  },
  ad_1003: {
    image_url: "https://picsum.photos/seed/ulbra-medicina/600/750",
    video_id: null,
    video_storage_url: null,
    video_transcript: null,
    video_retention: null,
  },
  ad_2001: {
    image_url: "https://picsum.photos/seed/ulbra-rmk/600/750",
    video_id: null,
    video_storage_url: null,
    video_transcript: null,
    video_retention: null,
  },
  ad_2002: {
    image_url: "https://picsum.photos/seed/ulbra-ig/600/750",
    video_id: null,
    video_storage_url: null,
    video_transcript: null,
    video_retention: null,
  },
  // Queda no hook — sem transcrição (pending)
  ad_3001: {
    image_url: "https://picsum.photos/seed/ulbra-campus/600/750",
    video_id: "vid_4401",
    video_storage_url: SAMPLE_VIDEOS.campus,
    video_transcript: null,
    video_retention: {
      plays: 24100,
      avg_watch_time_sec: 4.8,
      duration_sec: 24,
      p25: 41,
      p50: 28,
      p75: 18,
      p95: 11,
      p100: 7,
    },
  },
  // Queda no conteúdo — com transcrição longa
  ad_3002: {
    image_url: "https://picsum.photos/seed/ulbra-depoimento/600/750",
    video_id: "vid_4410",
    video_storage_url: SAMPLE_VIDEOS.depoimento,
    video_transcript:
      "Oi, eu sou a Marina e estudei na ULBRA.\nQuando eu entrei, eu não sabia se ia dar conta. Trabalhava de dia e estudava de noite.\nMas a estrutura, os professores e a comunidade fizeram toda a diferença.\nHoje eu atuo na área que eu sempre sonhei — e a formação prática foi o que me abriu portas.\nSe você tá em dúvida, vem conhecer. Sua história também pode começar aqui.\nInscrições abertas pro Vestibular 2026.",
    video_retention: {
      plays: 15600,
      avg_watch_time_sec: 9.1,
      duration_sec: 36,
      p25: 72,
      p50: 44,
      p75: 29,
      p95: 18,
      p100: 14,
    },
  },
  ad_4001: {
    image_url: "https://picsum.photos/seed/ulbra-ead/600/750",
    video_id: null,
    video_storage_url: null,
    video_transcript: null,
    video_retention: null,
  },
  ad_4002: {
    image_url: "https://picsum.photos/seed/ulbra-preco/600/750",
    video_id: null,
    video_storage_url: null,
    video_transcript: null,
    video_retention: null,
  },
};

/**
 * curso/praça/kind e os campos de objetivo são derivados em `normalizeRow`,
 * então o mock não os declara.
 */
type MockRow = Omit<
  AdInsightRow,
  | "objective"
  | "result_indicator"
  | "curso"
  | "praca"
  | "kind"
  | "recorte"
  | "reach"
  | "inline_link_clicks"
>;

export const MOCK_INSIGHTS: MockRow[] = RAW_MOCK_INSIGHTS.map((row) => {
  const media = CREATIVE_MEDIA[row.ad_id];
  return {
    ...row,
    image_url: media?.image_url ?? row.image_url,
    video_id: media?.video_id ?? row.video_id,
    video_storage_url: media?.video_storage_url ?? null,
    video_transcript: media?.video_transcript ?? null,
    video_retention: media?.video_retention ?? null,
  };
});
